services:
  - type: web
    name: cmms-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cmms-db
          property: connectionString

  - type: web
    name: cmms-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
